model_build:
  backbone: resnet18_slim
  sequence_modeling: abilstm
  model_head: attention
model_params:
  imgH: 32
  imgW: 280
  num_channels: 3
  max_len: 12
  hidden_size: 256
dataset:
  train_set: datasets/IDNum/idnum_train.tfrecords
  valid_set: datasets/IDNum/idnum_valid.tfrecords
  test_set: datasets/IDNum/idnum_test.tfrecords
training_param:
  optimizer: Adadelta
  num_epochs: 50
  batch_size: 32
  initial_lnr: 1.0
  num_warmup_steps: 100
  log_dir: checkpoints/IDNum/ResNet18s-abilstm256-attention
  log_interval: 200
  save_interval: 2000
